import type { Assignment } from "./types"

export const ASSIGNMENTS: Assignment[] = [
  {
    id: "a1",
    classId: "c1",
    title: "Assignment 1 — Linked Lists",
    description:
      "Implement a doubly-linked list with insert, delete, and reverse operations.",
    dueDate: "2026-04-01T23:59:00Z",
    maxScore: 100,
    type: "assignment",
    status: "graded",
    score: 92,
    hasIde: true,
  },
  {
    id: "a2",
    classId: "c1",
    title: "Assignment 2 — Binary Trees",
    description:
      "Implement BST with in-order, pre-order, and post-order traversal.",
    dueDate: "2026-04-15T23:59:00Z",
    maxScore: 100,
    type: "assignment",
    status: "submitted",
    hasIde: true,
  },
  {
    id: "a3",
    classId: "c1",
    title: "Midterm Quiz — Complexity Analysis",
    description: "25-question quiz on Big-O notation and complexity analysis.",
    dueDate: "2026-04-10T14:00:00Z",
    maxScore: 50,
    type: "quiz",
    status: "pending",
  },
  {
    id: "a4",
    classId: "c2",
    title: "Project 1 — Portfolio Page",
    description:
      "Build a responsive personal portfolio using HTML, CSS, and vanilla JS.",
    dueDate: "2026-04-05T23:59:00Z",
    maxScore: 100,
    type: "assignment",
    status: "graded",
    score: 88,
    hasIde: true,
  },
  {
    id: "a5",
    classId: "c2",
    title: "React Lab — Todo App",
    description:
      "Build a full CRUD todo app using React hooks and local state.",
    dueDate: "2026-04-20T23:59:00Z",
    maxScore: 100,
    type: "lab",
    status: "pending",
    hasIde: true,
  },
  {
    id: "a6",
    classId: "c3",
    title: "Lab 1 — Linear Regression",
    description: "Implement linear regression from scratch using NumPy.",
    dueDate: "2026-04-03T23:59:00Z",
    maxScore: 100,
    type: "lab",
    status: "graded",
    score: 95,
    hasIde: true,
  },
]
