import type { LeaderboardEntry } from "./types"

export const LEADERBOARD: LeaderboardEntry[] = [
  {
    studentId: "u3",
    classId: "c1",
    totalScore: 287,
    rank: 1,
    assignments: 3,
    avgScore: 95.7,
  },
  {
    studentId: "u1",
    classId: "c1",
    totalScore: 276,
    rank: 2,
    assignments: 3,
    avgScore: 92.0,
  },
  {
    studentId: "u5",
    classId: "c1",
    totalScore: 251,
    rank: 3,
    assignments: 3,
    avgScore: 83.7,
  },
  {
    studentId: "u2",
    classId: "c1",
    totalScore: 238,
    rank: 4,
    assignments: 3,
    avgScore: 79.3,
  },
  {
    studentId: "u1",
    classId: "c2",
    totalScore: 176,
    rank: 1,
    assignments: 2,
    avgScore: 88.0,
  },
  {
    studentId: "u4",
    classId: "c2",
    totalScore: 165,
    rank: 2,
    assignments: 2,
    avgScore: 82.5,
  },
  {
    studentId: "u5",
    classId: "c2",
    totalScore: 154,
    rank: 3,
    assignments: 2,
    avgScore: 77.0,
  },
  {
    studentId: "u2",
    classId: "c2",
    totalScore: 148,
    rank: 4,
    assignments: 2,
    avgScore: 74.0,
  },
  {
    studentId: "u3",
    classId: "c3",
    totalScore: 190,
    rank: 1,
    assignments: 2,
    avgScore: 95.0,
  },
  {
    studentId: "u1",
    classId: "c3",
    totalScore: 185,
    rank: 2,
    assignments: 2,
    avgScore: 92.5,
  },
  {
    studentId: "u4",
    classId: "c3",
    totalScore: 172,
    rank: 3,
    assignments: 2,
    avgScore: 86.0,
  },
  {
    studentId: "u5",
    classId: "c3",
    totalScore: 155,
    rank: 4,
    assignments: 2,
    avgScore: 77.5,
  },
]
