import type { Material } from "./types"

export const MATERIALS: Material[] = [
  {
    id: "mat1",
    classId: "c1",
    title: "CS301 Syllabus — Spring 2026",
    type: "pdf",
    url: "#",
    uploadedBy: "t1",
    uploadedAt: "2026-03-01T00:00:00Z",
    size: "180 KB",
    description: "Full course syllabus including grading policy and schedule.",
  },
  {
    id: "mat2",
    classId: "c1",
    title: "Lecture 1 — Arrays & Linked Lists",
    type: "slide",
    url: "#",
    uploadedBy: "t1",
    uploadedAt: "2026-03-03T00:00:00Z",
    size: "2.4 MB",
    description:
      "Slides covering contiguous vs. linked memory, insertion/deletion complexity.",
  },
  {
    id: "mat3",
    classId: "c1",
    title: "Lecture 2 — Stacks & Queues",
    type: "slide",
    url: "#",
    uploadedBy: "t1",
    uploadedAt: "2026-03-10T00:00:00Z",
    size: "1.9 MB",
  },
  {
    id: "mat4",
    classId: "c1",
    title: "Binary Trees Walkthrough",
    type: "video",
    url: "#",
    uploadedBy: "t1",
    uploadedAt: "2026-03-17T00:00:00Z",
    size: "320 MB",
    description: "Recorded walkthrough of binary tree traversal algorithms.",
  },
  {
    id: "mat5",
    classId: "c2",
    title: "WD101 Starter Kit",
    type: "code",
    url: "#",
    uploadedBy: "t2",
    uploadedAt: "2026-03-01T00:00:00Z",
    size: "12 MB",
    description: "HTML/CSS/JS boilerplate for the first 4 weeks.",
  },
  {
    id: "mat6",
    classId: "c2",
    title: "React Hooks Reference",
    type: "pdf",
    url: "#",
    uploadedBy: "t2",
    uploadedAt: "2026-03-20T00:00:00Z",
    size: "560 KB",
  },
  {
    id: "mat7",
    classId: "c3",
    title: "ML Chapter 1–3 Notes",
    type: "pdf",
    url: "#",
    uploadedBy: "t1",
    uploadedAt: "2026-03-05T00:00:00Z",
    size: "1.1 MB",
  },
  {
    id: "mat8",
    classId: "c3",
    title: "Linear Regression Jupyter Notebook",
    type: "code",
    url: "#",
    uploadedBy: "t1",
    uploadedAt: "2026-03-12T00:00:00Z",
    size: "45 KB",
    description: "Hands-on notebook for linear & logistic regression.",
  },
]
