import type { User } from "./types"

export const USERS: User[] = [
  {
    id: "u1",
    name: "Alex Rivera",
    email: "alex@eduflow.io",
    role: "student",
    avatar: "AR",
    institution: "Horizon Institute",
    enrolledClassIds: ["c1", "c2", "c3"],
    semester: "Spring 2026",
    gpa: 3.7,
  },
  {
    id: "u2",
    name: "Jordan Kim",
    email: "jordan@eduflow.io",
    role: "student",
    avatar: "JK",
    institution: "Horizon Institute",
    enrolledClassIds: ["c1", "c2"],
    semester: "Spring 2026",
    gpa: 3.4,
  },
  {
    id: "u3",
    name: "Sam Chen",
    email: "sam@eduflow.io",
    role: "student",
    avatar: "SC",
    institution: "Horizon Institute",
    enrolledClassIds: ["c1", "c3"],
    semester: "Spring 2026",
    gpa: 3.9,
  },
  {
    id: "u4",
    name: "Morgan Walsh",
    email: "morgan@eduflow.io",
    role: "student",
    avatar: "MW",
    institution: "Horizon Institute",
    enrolledClassIds: ["c2", "c3"],
    semester: "Spring 2026",
    gpa: 3.2,
  },
  {
    id: "u5",
    name: "Taylor Brooks",
    email: "taylor@eduflow.io",
    role: "student",
    avatar: "TB",
    institution: "Horizon Institute",
    enrolledClassIds: ["c1", "c2", "c3"],
    semester: "Spring 2026",
    gpa: 2.9,
  },
  {
    id: "t1",
    name: "Dr. Priya Nair",
    email: "priya@eduflow.io",
    role: "teacher",
    avatar: "PN",
    institution: "Horizon Institute",
    taughtClassIds: ["c1", "c3"],
  },
  {
    id: "t2",
    name: "Prof. Carlos Mendes",
    email: "carlos@eduflow.io",
    role: "teacher",
    avatar: "CM",
    institution: "Horizon Institute",
    taughtClassIds: ["c2"],
  },
  {
    id: "a1",
    name: "Admin User",
    email: "admin@eduflow.io",
    role: "admin",
    avatar: "AU",
    institution: "Horizon Institute",
  },
]
